export {
  POSITION_MIN_MOVE_METERS,
  POSITION_UPDATE_MIN_INTERVAL_MS,
  NEARBY_RADIUS_METERS_DEFAULT,
  TILE_SIZE_M,
  TILE_LOAD_RADIUS,
  TILE_UPSAMPLE_FACTOR,
  TILE_DRACO,
} from './game-runtime.js';
